### ISSUE TITLE
Missing file "ground_truth.mat"

### ISSUE THREAD

**Issue by amiltonwong** [stephenphillips42/erl_egomotion#1]
Hi, @stephenphillips42 ,

After I run "RunUAVTests", it throws the following error:

Error using load
Unable to read file 'C:\home\stephen\Documents\Research\data\air-ground-data\ground_truth.mat'. No such file or directory.
Error in RunUAVTests (line 3)
gt = load(fullfile(basdir,'ground_truth.mat'));

I can't find the ground truth file: "ground_truth.mat" in your package,  any suggestion to fix it  ?

Thanks ~
Milton

**Comment by stephenphillips42** [comment]
I didn't mean to push this file to the repo - it was supposed to be just some scratch code. Sorry, my mistake. I have removed the file now. What did you want with these tests? Just to run the code or to compare it to ground truth?

**Comment by amiltonwong** [comment]
Hi, @stephenphillips42,

Thanks for your reply. I see that you had deleted file RunUAVTests.m in repository.
Now I run file "init.m" , then "./Tests/sample.m"  , and got the output as follows: 
https://goo.gl/AK4Ijp

Are those what we should expect after running your package?

Thanks~
Milton

**Comment by stephenphillips42** [comment]
Yes these are working as expected.

**Comment by amiltonwong** [comment]
Thanks :)
