### ISSUE TITLE
Undefined function or variable 'detectMinEigenFeatures'?

### ISSUE THREAD

**Issue by wqren** [stephenphillips42/erl_egomotion#2]
Hi,
I ran the Sample.m in Tests and got the following errors:
Undefined function or variable 'detectMinEigenFeatures'.

Error in ImageFlow (line 23)
            points = detectMinEigenFeatures(img0,'MinQuality',minQuality);

Error in Sample (line 7)
flow = ImageFlow(Im1,Im2,'K',ld.K,'trueT',ld.trueT,'trueOmega',ld.trueOmega);

It seems that there is no implementation for  detectMinEigenFeatures.

**Comment by wqren** [comment]
I found that this is a matlab function. Maybe there is something wrong with my matlab.

**Comment by stephenphillips42** [comment]
Hello wqren. I apologize for the confusion. After seeing this issue, I have updated the documentation a little, and hopefully the dependencies will be more clear in the future. I hope to add some of those dependencies to the repo so that it can be more self-contained.
