### ISSUE TITLE
Missing RobustLiftedCostFunction

### ISSUE THREAD

**Issue by mljack** [stephenphillips42/erl_egomotion#3]
Some files are not uploaded to github.

With this code
```
c = CostFunctionFactory('RobustLifted',flow);
```
Matlab complains that:
```
Error using RobustLiftedCostFunction
The specified superclass 'ZhangMatrixCostFunction' contains a parse error, cannot be found on MATLAB's search path, or is
shadowed by another file with the same name.
```

**Comment by stephenphillips42** [comment]
Hello mljack, this was a naming bug from an older version of the code. It should be fixed now with the latest push. Let me know if it works for you.

**Comment by mljack** [comment]
It works fine now.
Thank a lot for your quick kind response!

**Comment by stephenphillips42** [comment]
No problem!
